// Generated by CoffeeScript 1.6.2
(function() {
  var back, fwd, logs;

  this.ta = document.querySelector("textarea");

  this.sp = document.querySelector("span");

  ta.addEventListener("keydown", function(e) {
    return logs(e);
  });

  fwd = function(e) {
    if (e.target.value.length < 5) {
      return sp.innerText = 5 - (e.target.value.length + 1) + " characters left";
    } else {
      return sp.innerText = 5 - e.target.value.length + " characters left";
    }
  };

  back = function(e) {
    if (e.keyCode === 8) {
      if (e.target.value.length > 0) {
        return sp.innerText = 5 - (--e.target.value.length) + " characters left";
      } else {
        return sp.innerText = "5 characters left";
      }
    }
  };

  logs = function(e) {
    fwd(e);
    back(e);
    if (e.keyCode === 13) {
      console.log(e.target.value);
      sp.innerText = "5 characters left";
      e.preventDefault();
      return e.target.value = "";
    }
  };

}).call(this);
