// Generated by CoffeeScript 1.6.2
(function() {
  this.cBS = {};

  cBS.counter = {
    init: function() {
      this.cacheElements();
      return this.bindEvents();
    },
    cacheElements: function() {
      this.tarea = document.querySelector("textarea");
      return this.counter = document.querySelector("span");
    },
    bindEvents: function() {
      var _this = this;

      this.tarea.addEventListener("keydown", function(e) {
        return _this.count(e);
      });
      this.tarea.addEventListener("focus", function(e) {
        return e.target.placeholder = "";
      });
      return this.tarea.addEventListener("blur", function(e) {
        return e.target.placeholder = "Enter your text";
      });
    },
    fwd: function(e) {
      if (e.target.value.length < 255) {
        return this.counter.innerText = 255 - (e.target.value.length + 1) + " characters left";
      } else {
        return this.counter.innerText = 255 - e.target.value.length + " characters left";
      }
    },
    back: function(e) {
      if (e.keyCode === 8) {
        if (e.target.value.length > 0) {
          return this.counter.innerText = 255 - (--e.target.value.length) + " characters left";
        } else {
          return this.counter.innerText = "255 characters left";
        }
      }
    },
    count: function(e) {
      this.fwd(e);
      this.back(e);
      if (e.keyCode === 13) {
        alert(e.target.value);
        this.counter.innerText = "255 characters left";
        e.preventDefault();
        return e.target.value = null;
      }
    }
  };

  cBS.counter.init();

  cBS.style = {
    init: function() {
      this.cacheElements();
      return this.bindEvents();
    },
    cacheElements: function() {
      this.bgColor = document.querySelector("select[name=bg-color]");
      this.textColor = document.querySelector("select[name=text-color]");
      this.fontFamily = document.querySelector("select[name=font-family]");
      return this.fontSize = document.querySelector("select[name=font-size]");
    },
    bindEvents: function() {
      this.bgColor.addEventListener("click", function(e) {
        return cBS.counter.tarea.style.backgroundColor = e.target.value;
      });
      this.textColor.addEventListener("click", function(e) {
        return cBS.counter.tarea.style.color = e.target.value;
      });
      this.fontFamily.addEventListener("click", function(e) {
        return cBS.counter.tarea.style.fontFamily = e.target.value;
      });
      return this.fontSize.addEventListener("click", function(e) {
        return cBS.counter.tarea.style.fontSize = e.target.value;
      });
    }
  };

  cBS.style.init();

}).call(this);
